# Generated by Django 4.2.1 on 2023-06-01 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_classroom_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='classroom_files/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='app.classroom')),
            ],
            options={
                'verbose_name': 'Classroom Resource',
                'verbose_name_plural': 'Classroom Resources',
                'db_table': 'ClassroomResource',
            },
        ),
    ]
