# Generated by Django 4.2.1 on 2023-06-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_classroomresource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroomresource',
            options={'ordering': ['-created', '-updated'], 'verbose_name': 'Classroom Resource', 'verbose_name_plural': 'Classroom Resources'},
        ),
        migrations.AddField(
            model_name='classroom',
            name='profile_pic',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
